# Generated by Django 4.1.5 on 2023-01-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fund_image_fund_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
